### PR TITLE
Fix count not being set correctly on dense storage structs.

### LINKED ISSUE #356: (NMATRIX)-> count is never set to actual number of elements in the nmatrix
The main nmatrix data structure contains [an element called 'count'](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/nmatrix.h#L152) which is supposed to store the total number of elements in an NMatrix.

It so happens, that once the `count` struct element is set to `1` in [` nm_dense_storage_create_dummy`](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/storage/dense/dense.cpp#L205), it is never set to the actual number of elements that are present in the nmatrix, and hence the `count` element remains set a `1` irrespective of the number of elements present in the matrix.

One might argue that `NMatrix#count` works, but thats only in the ruby API and that too because the `Enumerable` ruby module has been included in the NMatrix class. The C API still malfunctions.

### PR DESCRIPTION
**Pull request by cjfuller**
(Fixes #356).

I have no idea why I had count set to 1 originally and then never updated it.
It should be 0 while elements is NULL (since there are no elements at all),
and then updated to the correct number in nm_dense_storage_create, when
elements is actually set to something.

An alternate strategy considered was to set count to the value returned by
nm_storage_count_max_elements in nm_dense_storage_create_dummy itself, but this
seemed more likely to cause a segfault down the road to me (since it might be
likely to iterate over elements from 0 to count).

### CODE REVIEW

File: ext/nmatrix/storage/dense/dense.cpp [hunk 1]
```diff
@@ -237,13 +237,15 @@ DENSE_STORAGE* nm_dense_storage_create(nm::dtype_t dtype, size_t* shape, size_t
...
-    
+    s->count = count;
+
     if (dtype == nm::RUBYOBJ)
       nm_unregister_values(reinterpret_cast<VALUE*>(elements), elements_length);
 
   } else {
 
     s->elements = NM_ALLOC_N(char, DTYPE_SIZES[dtype]*count);
+    s->count = count;
```
Comment (v0dro) [inline ext/nmatrix/storage/dense/dense.cpp]: Why not do the `s->count = count` after the if-else block?

**Comment by v0dro** [comment]
This fix does not seem to be working. I'm still getting the `count` variable as `1` when calling it in an extension.
